import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'androidx.navigation.safeargs.kotlin'
    id 'kotlin-parcelize'
    alias(libs.plugins.compose.compiler)
    id 'kotlin-kapt'
    alias(libs.plugins.kotlin.ksp)
}

def localProperties = new Properties()
localProperties.load(new FileInputStream(rootProject.file("local.properties")))
android {
    compileSdk = 36
    namespace = "code.name.monkey.lost"

    defaultConfig {
        minSdk = 26 // Changed from 23 to 26
        targetSdk = 36

        vectorDrawables.useSupportLibrary = true

        applicationId = namespace
        versionCode = 10651
        versionName = "6.5.1"
        buildConfigField("String", "GEMINI_API_KEYS", "\"${getProperty(getProperties('local.properties'), 'GEMINI_API_KEYS')}\"")
        buildConfigField("String", "GOOGLE_PLAY_LICENSING_KEY", "\"${getProperty(getProperties('public.properties'), 'GOOGLE_PLAY_LICENSE_KEY')}\"")
    }

    def signingProperties = getProperties('lost.properties')
    def theSigningConfig
    if (signingProperties != null) {
        theSigningConfig = signingConfigs.create("release") {
            storeFile = file(getProperty(signingProperties, 'storeFile'))
            keyAlias = getProperty(signingProperties, 'keyAlias')
            storePassword = getProperty(signingProperties, 'storePassword')
            keyPassword = getProperty(signingProperties, 'keyPassword')
        }
    } else {
        theSigningConfig = signingConfigs.debug
    }

    buildTypes {
        release {
            shrinkResources = true
            minifyEnabled = true
            proguardFiles(getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro')
            signingConfig = theSigningConfig
        }
        debug {
            signingConfig = theSigningConfig
            applicationIdSuffix = ".debug"
            versionNameSuffix = " DEBUG"
        }
    }

    flavorDimensions += "version"
    productFlavors {
        normal {
            dimension = "version"
        }
        fdroid {
            dimension = "version"
        }
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
        compose = true
    }

    kotlin {
        jvmToolchain(21)

        compilerOptions {
            freeCompilerArgs.add("-Xannotation-default-target=param-property")
            jvmTarget.set(JvmTarget.JVM_21)
        }
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE', 'META-INF/NOTICE', 'META-INF/java.properties']
        }
    }

    lint {
        abortOnError = true
        warning += ['ImpliedQuantity', 'Instantiatable', 'MissingQuantity', 'MissingTranslation', 'StringFormatInvalid']
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = "21"
    }

    composeOptions {
        kotlinCompilerExtensionVersion = libs.versions.androidxComposeCompiler.get()
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    configurations.configureEach {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
}

kapt {
    correctErrorTypes = true
    useBuildCache = true
    arguments {
        // arg("dagger.fastInit", "enabled")
        // arg("dagger.formatGeneratedSource", "disabled")
        // dagger.gradle.incremental is deprecated in newer versions
    }
}

def getProperties(String fileName) {
    Properties properties = new Properties()
    def file = rootProject.file(fileName)
    if (file.exists()) {
        file.withInputStream { stream -> properties.load(stream) }
    } else {
        properties = null
    }
    return properties
}

static def getProperty(Properties properties, String name) {
    return properties?.getProperty(name) ?: "$name missing"
}

dependencies {
    implementation(project(':appthemehelper'))
    implementation(libs.gridLayout)

    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.constraintLayout)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.preference.ktx)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.palette.ktx)
    implementation(libs.androidx.mediarouter)
    implementation(libs.androidx.security.crypto)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.androidx.datastore.core)
    implementation(project(":innertube"))
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.serialization.json)
    implementation(libs.timber)
    implementation libs.androidx.lifecycle.service
    // Cast Dependencies
    normalImplementation(libs.google.play.services.cast.framework)
    implementation(libs.coil)
    implementation(libs.coil.network.okhttp)
    // WebServer by NanoHttpd
    normalImplementation(libs.nanohttpd)
    implementation(libs.room.runtime)
    implementation(libs.androidx.navigation.runtime.ktx)
    implementation(libs.androidx.navigation.fragment.ktx)
    implementation(libs.androidx.navigation.ui.ktx)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)

    implementation(libs.koin.core)
    implementation(libs.koin.android)

    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.lifecycle.livedata.ktx)
    implementation(libs.androidx.lifecycle.common.java8)

    implementation(libs.androidx.core.splashscreen)

    normalImplementation(libs.google.feature.delivery)
    normalImplementation(libs.google.play.review)

    implementation(libs.hilt.navigation)
    ksp(libs.room.compiler)
    implementation(libs.hilt)
    kapt(libs.hilt.compiler)

    implementation(libs.android.material)

    implementation(libs.retrofit)
    implementation(libs.retrofit.converter.gson)
    implementation(libs.okhttp3.logging.interceptor)

    implementation(libs.afollestad.material.dialogs.core)
    implementation(libs.afollestad.material.dialogs.input)
    implementation(libs.afollestad.material.dialogs.color)
    implementation(libs.afollestad.material.cab)


    implementation(libs.kotlinx.coroutines.android)

    implementation(libs.glide)
    ksp(libs.glide.ksp)
    implementation(libs.glide.okhttp3.integration)

    implementation(libs.advrecyclerview)
    implementation(libs.fadingedgelayout)
    implementation(libs.keyboardvisibilityevent)
    implementation(libs.jetradarmobile.android.snowfall)
    implementation(libs.chrisbanes.insetter)

    implementation(libs.org.eclipse.egit.github.core)
    implementation(libs.jaudiotagger)
    implementation 'org.slf4j:slf4j-nop:1.7.32' // Added to resolve SLF4J warning
    normalImplementation(libs.android.lab.library)
    implementation(libs.slidableactivity)
    implementation(libs.material.intro)
    implementation(libs.dhaval2404.imagepicker)
    implementation(libs.fastscroll.library)
    implementation(libs.customactivityoncrash)
    implementation(libs.tankery.circularSeekBar)
    implementation(libs.androidx.exoplayer)
    // Jetpack Compose
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3) // Assuming Material 3, adjust if using Material 2
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose) // For Jetpack Navigation with Compose

    // Optional - For tooling (like live preview in Android Studio)
    debugImplementation(libs.androidx.compose.ui.tooling)
    // Optional - For UI tests
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}